from django.urls import path
from . import views
from django.conf.urls import url
urlpatterns = [
    path('', views.home, name='home'),
    path('login',views.login,name='login'),
    path('join',views.join,name='join'),
    path('add_club',views.add_club,name='add_club'),
    path('remove_club',views.remove_club,name='remove_club'),
    path('comments',views.comments,name='comments'),
    path('like',views.like,name='like'),
    path('dislike',views.dislike,name='dislike'),
    path('create_post',views.create_post,name='create_post'),
    path('conduct_poll',views.conduct_poll,name='conduct_poll'),
    path('participate_poll',views.participate_poll,name='participate_poll'),
    path('register_event',views.register_event,name='register_event'),
    path('notifications_seen',views.notifications_seen,name='notifications_seen'),
    path('student/<int:s_id>',views.student,name='student'),
    path('Club_Admin/<int:ca_id>',views.Club_Admin,name='Club_Admin'),
    path('Super_Admin/<int:sa_id>',views.Super_Admin,name='Super_Admin'),
    path('organize_event',views.organize_event,name='organize_event'),
    path('leave_club',views.leave_club,name='leave_club'),
    url('^dashboard/(?P<token>.+)$',views.dashboard,name='dashboard'),
    path('student_profile/<int:s_id>',views.student_profile,name='student_profile'),
    path('clubs_joined',views.clubs_joined,name='clubs_joined'),
    path('events_registered',views.events_registered,name='events_registered'),
    path('edit_profile_pic',views.edit_profile_pic,name='edit_profile_pic'),
    path('EditDetails',views.EditDetails,name='EditDetails'),
    path('DelImage',views.DelImage,name='DelImage'),
    path('postsUploaded/<int:s_id>',views.postsUploaded,name='postsUploaded'),
    path('Details/<int:s_id>/<int:p_id>',views.Details,name='Details'),
    path('EditPost',views.EditPost,name='EditPost'),
    path('DelPost/<int:s_id>/<int:p_id>',views.DelPost,name='DelPost'),
    path('edit_profile_pic_admin',views.edit_profile_pic_admin,name='edit_profile_pic_admin'),
    path('EditDetails_admin',views.EditDetails_admin,name='EditDetails_admin'),
    path('DelImage_admin',views.DelImage_admin,name='DelImage_admin'),
    path('club_events_admin/<int:sa_id>',views.club_events_admin,name='club_events_admin'),
    path('super_admin_posts/<int:sa_id>',views.super_admin_posts,name='super_admin_posts'),
    path('club_admin_profile/<int:ca_id>',views.club_admin_profile,name='club_admin_profile'),
    path('EditDetails_club_admin',views.EditDetails_club_admin,name='EditDetails_club_admin0.'),
    path('EditDP_club_admin',views.EditDP_club_admin,name='EditDP_club_admin'),
    path('DelImage_club_admin',views.DelImage_club_admin,name='DelImage_club_admin'),
]

