# Generated by Django 2.1.2 on 2018-11-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_active_status',
            field=models.BooleanField(default=True),
        ),
    ]
