# Generated by Django 2.1.2 on 2018-10-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0006_auto_20181025_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_media',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='leave_club_log',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='leave_club_log',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='poll_options',
            name='poll_id',
        ),
        migrations.RemoveField(
            model_name='poll_participation',
            name='option_id',
        ),
        migrations.RemoveField(
            model_name='poll_participation',
            name='poll_id',
        ),
        migrations.RemoveField(
            model_name='poll_participation',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='event_media',
        ),
        migrations.DeleteModel(
            name='leave_club_log',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='media',
        ),
        migrations.DeleteModel(
            name='poll',
        ),
        migrations.DeleteModel(
            name='poll_options',
        ),
        migrations.DeleteModel(
            name='poll_participation',
        ),
    ]
