# Generated by Django 2.1.2 on 2018-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0010_auto_20181025_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.IntegerField(),
        ),
    ]
