# Generated by Django 2.1.2 on 2018-10-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0011_auto_20181026_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer_id',
            field=models.IntegerField(),
        ),
    ]
