# Generated by Django 2.1.2 on 2018-10-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0013_auto_20181026_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=30)),
                ('media', models.FileField(blank=True, upload_to='')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CREW.post')),
            ],
        ),
    ]
