# Generated by Django 2.1.2 on 2018-10-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0015_auto_20181028_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_media',
            name='media',
            field=models.FileField(upload_to='post_media'),
        ),
    ]
