# Generated by Django 2.1.2 on 2018-10-28 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0016_auto_20181028_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='logout_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logout_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CREW.user')),
            ],
        ),
        migrations.CreateModel(
            name='remove_club_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CREW.club')),
            ],
        ),
        migrations.AddField(
            model_name='poll_options',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave_club_log',
            name='date_of_leaving',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
