# Generated by Django 2.1.2 on 2018-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0022_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_dp',
            new_name='club_logo',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_added_by',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_advisor',
        ),
        migrations.AddField(
            model_name='club',
            name='club_description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
