# Generated by Django 2.1.2 on 2018-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0023_auto_20181028_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos'),
        ),
    ]
