# Generated by Django 2.1.2 on 2018-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0025_auto_20181029_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_options',
            name='image',
            field=models.ImageField(blank=True, upload_to='poll_media/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
