# Generated by Django 2.1.2 on 2018-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0026_poll_options_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(default='Single', max_length=10),
            preserve_default=False,
        ),
    ]
