# Generated by Django 2.1.2 on 2018-10-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CREW', '0027_poll_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_options',
            name='image',
            field=models.ImageField(blank=True, upload_to='poll_media/polls'),
        ),
    ]
